### ISSUE TITLE
Fatiando User Survey 2022

### ISSUE THREAD

**Issue by leouieda** [fatiando/community#63]
In our [2022-08-19](https://github.com/fatiando/community/blob/main/development-calls/2022.md#2022-08-19) Weekly Call we decided to run a survey to gather information about our community. The goals are to help guide future project directions and gather data that can be used to support future grant applications.

This issue is to track progress of developing, rolling out the survey, and analysing the results.

**Tasks:**

- [x] Start a survey in Google Forms and ask for feedback (@leouieda)
- [x] Post a preview of the survey to this issue for further feedback (@leouieda)
- [ ] Decide on a closing date for the survey
- [ ] Publish the survey (paste link here). Target date: 2022/09/12 (@leouieda)
- [ ] Add a top banner to the website with a link to the survey like the t-shirt one (any takers?)
- [ ] Write a social media message that we can share on all platforms (@MGomezN ?)
- [x] Create a banner image to use on social media (@leouieda). Here it is: https://github.com/fatiando/logo/blob/main/banner/fatiando-user-survey.png
- [ ] Share the survey:
  - Twitter (@MGomezN) 
  - LinkedIn (@leouieda)
  - ResearchGate (@leouieda)
  - GitHub Discussions announcement as a pinned post (volunteers?)
  - Software Underground post to `#general` (volunteers?)
  - SimPEG slack (@santisoler ?)
  - GSH Potential Fields group (@andieie ?)
  - Anywhere else?
  - Please also send to personal connections that may use Fatiando.
  - Post links social media on Slack/Matrix for retweets/reshares
- [ ] Share again 1 week before the deadline:
  - Twitter (@MGomezN) 
  - LinkedIn (@leouieda)
  - ResearchGate (@leouieda)
  - Software Underground post to `#general`
- [ ] Share again 1 day before the deadline:
  - Twitter (@MGomezN) 
  - LinkedIn (@leouieda)
  - ResearchGate (@leouieda)
  - Software Underground post to `#general`

<details>
<summary>Survey preview (screenshot)</summary>

![Survey preview (screenshot)](https://user-images.githubusercontent.com/290082/188836556-e21481d2-24bc-4a6a-9450-2175bd3975e0.png)

</details>

**Comment by leouieda** [comment]
**Post survey tasks:**

- [ ] Initial pass over the survey data (team with access are @leouieda @aguspesce @santisoler @MGomezN)
- [ ] Compile main take aways from the written responses
- [ ] Create a spreadsheet with personal information and written responses removed (could have identifiable information in those) that can be published
- [ ] Make some graphs of the multiple choice questions from the anonymized data
- [ ] Create a page under https://www.fatiando.org/community/ about the survey results. Includes interpretation, interactive figures, links to download the data (upload a CSV to the website). Could be a Jupyter notebook in Markdown format executed using jupyter-sphinx.
- [ ] Post about the survey results (short thread + link to the page).

Volunteers for any of these would be welcome! Only exception is access to the full data which I'd prefer to keep limited since there could be personal information in there that we don't want to make public.

**Comment by leouieda** [comment]
Questions to add:

* How did you first hear about Fatiando?
* Any specific use case you’d like to share? (papers, projects, etc)

**Comment by aguspesce** [comment]
@leouieda, I can post it in Geolatinas and Software Underground

**Comment by santisoler** [comment]
> @leouieda, I can post it in Geolatinas and Software Underground

Awesome! Feel free to open a PR whenever you want. There's no need to wait until the deadline. We can merge it one day before.

**Comment by santisoler** [comment]
> Questions to add:
> 
>     * How did you first hear about Fatiando? (talk, paper citation, word of mouth, social media, Transform, search, entered group already using)
> 
>     * Any specific use case you’d like to share? (papers, projects, etc)

I love these two. Feel free to add them!

**Comment by aguspesce** [comment]
@leouieda  and @santisoler I am working to create the survey alert for the website

**Comment by aguspesce** [comment]
@leouieda and @santisoler. I finished the [PR](https://github.com/fatiando/website/pull/72) for the survey alert. 

It is necessary to add the link to the survey, and maybe you can better ideas for the text. Please, take a look on It

**Comment by leouieda** [comment]
Social media message:

> 📣 Calling all users of Pooch/Verde/Harmonica/Boule/Fatiando: We need your feedback! Please fill out this short survey (5-10min) LINKTOSURVEY
>
> Our goal is to get to know our community better and tailor development to your needs!
> ![](https://github.com/fatiando/logo/raw/main/banner/fatiando-user-survey.png)
> Alt: Fatiando a Terra User Survey 2022. Fill it out today! Should only take 5-10min.

Any thoughts or changes? cc @MGomezN our social media guru ❤️

**Comment by aguspesce** [comment]
@leouieda ... The survey works fine!

**Comment by MGomezN** [comment]
> 
Some thoughts. Thinking on my personal case. 
So narcissist this Mariana!

- [ ] The survey asks about the country of _residence_. What if we add nationality? 

- [ ] to Include a question about native languages? Or  English level?
What I really want to know is if people complain about documentation/tutorials not being clear enough, is it because maybe they don't have the English level required to understand it?
 Perhaps the options can be:
a) I find the documentation clear. I have an advanced English level.
b) Documentation is not clear. I have an advanced English level
c) Documentation is clear. I have a basic English level
d) Documentation is not clear. I have a basic English level
e) Documentation seems straightforward, but my English level and lack of fundamental concepts make reading difficult. (Mariana's option) jajaj

- [ ] Maybe the option to reply to the "text" questions in their native language? This is because I can fill out a survey quickly and with more sincere and profound thinking in my language, while in English takes me 3-4 times more to do it. So I usually skip text questions unless I have something significant to say. In this survey, they are optional.

- [ ]  If you agree with the last point, we can add a question saying, " We wish to remove the language barriers, so you can reply to these questions in any language you feel comfortable with. 
Please select the language you prefer to reply, " then a list of options... 
I can commit to translating the answers to English after :) (with my friend Google translate) 

- [ ] is age not important? Maybe a question like: " What is your age?
a) 15-20
b)20-30
c) 30-40
d) 40-50
e) 50-60
Other??

**Comment by MGomezN** [comment]
> Social media message:
> 
> > 📣 Calling all users of Pooch/Verde/Harmonica/Boule/Fatiando: We need your feedback! Please fill out this short survey (5-10min) LINKTOSURVEY
> > Your answers will let us know our community better and tailor development to your needs!
> > ![](https://github.com/fatiando/logo/raw/main/banner/fatiando-survey.png)
> > Alt: Fatiando a Terra Community Survey 2022. Fill it out today! Should only take 5-10min.
> 
> Any thoughts or changes? cc @MGomezN our social media guru ❤️

 I love it :) But I will ask my guru Abraham Reyes in case we can improve to make it irresistible to reply

**Comment by MGomezN** [comment]
My guru's suggestion:
https://www.fakewhats.com/free
 :laughing:  :laughing: 

![fakewhatsappfatiandosurvey](https://user-images.githubusercontent.com/29388479/189304150-09b6d863-89dc-44e1-aa74-e91782d76894.png)

**Comment by leouieda** [comment]
😆 Love it! Since our goal is to post about this a few times, we can use the different messages.

**Comment by leouieda** [comment]
> The survey asks about the country of residence. What if we add nationality?

This can get complicated fast since people can have multiple nationalities and may be living out of their country of birth for most of their lives. So being from Brazil and living in the UK doesn't necessarily say much about my culture/upbringing. My daughter is Brazilian (not a UK citizen) but was born and raised in the UK.

If the goal is to find out if someone is fluent in English or not, then maybe we could just ask that as you suggested: "What is your level of fluency in the English language?" with options "Low, Moderate, High, Fluent, Native". Would that be OK?

> What I really want to know is if people complain about documentation/tutorials not being clear enough, is it because maybe they don't have the English level required to understand it?

That's a very good point! Maybe we could include a question about what people think of our documentation? 
* "How would you rate the overall quality of our documentation?" with "Don't know/Haven't used, Very Poor, Poor/Confusing, Neither good nor bad, Good/Mostly clear, Excellent". It could list all projects including the tutorial/videos. 
* This could be followed up by an optional written question "Do you have any suggestions on how we could improve our documentation and learning resources?". This could cover things like "it's too technical" or "my English isn't so good so a Spanish translation would be great".

What do you think?

> Maybe the option to reply to the "text" questions in their native language? 

Great idea! I can put in text in the description of that section saying: 

"The preferred language for your answers is English but we don't want language to be a barrier for your participation. Please feel free to write in another language if you feel more comfortable doing so. However, our team only includes fluent speakers of English, Portuguese, and Spanish. Other languages will be translated using Google Translator."

How about that? 

> is age not important? Maybe a question like: " What is your age?

Does it matter? I feel like we shouldn't ask personal information like this unless there is a good reason for doing so. Personally, I don't know if I'd use this. But if there is a legitimate reason then I'm happy to include.

**Comment by leouieda** [comment]
Thanks for the feedback @MGomezN! Always appreciate your very thoughtful points 🙂

**Comment by leouieda** [comment]
Oh, and it would be great is the message about answering in another language was included in all officially supported languages 🇧🇷 🇲🇽

**Comment by MGomezN** [comment]
Maybe the words "nationality" and "age" are not reflecting what I really want to ask. 

Rocio in GeoLatinas shared this words one day about an opportunity to write a short article in Nature:


" Terminology: requested them to go from Hispanic Heritage, to “Hispanic, LatinAmerican and Latinx Heritage Month” on the form text, to honor how using those terms are a push for some of us, as we identify differently (by country, gender inclusive and/or other culturally relevant terms like Chicane). 
 
 Identity: requested using our country of heritage on the article, even with flags if possible."

So, what I'm looking for is a questions to have an idea about
"cultural diversity" of people using Fatiando. 

Are these tools used by a wide range of people with a broad range of programming skills? And educational levels? 
Bachelors? Posdocs? 
Phds?  
Assessment of the "accessibility" of this software is maybe something future grants applications are interested in.

**Comment by leouieda** [comment]
Ah right, I see what you mean. So how about we ask:

"What is your country of heritage?" 

Your country of heritage is the country with which you identify culturally. It may or may not be the same as your country of residence or country of birth.

> Are these tools used by a wide range of people with a broad range of programming skills? And educational levels?

I'll include questions about programming skill level and educational level as well. Good catch!

>  Assessment of the "accessibility" of this software is maybe something future grants applications are interested in.

Yes 100%! 

I have added the questions above to the survey: https://forms.gle/X2CUVAc8aD8j1Srg7

@aguspesce @MGomezN could you please have another go at the survey to see if it's OK?

**Comment by MGomezN** [comment]
@leouieda some suggestions:

- What is *your* affiliation?

- What is your level of education? --> Maybe add _formal_ or __academic_ education? since people can argue education is not only academic.

-  I suggest bringing this paragraph to the first page of the survey: "The preferred language for your answers is English but we don't want language to be a barrier for your participation. Please feel free to write in another language if you feel more comfortable doing so. However, keep in mind that our survey team only includes fluent speakers of English, Portuguese, and Spanish. Other languages will be translated using Google Translator."

Some short questions require writing before page 4. I guess people can feel enthusiastic if they know from the beginning they can reply in any language they prefer. 
- How did you manage to include the list of countries!? Awesome! If possible, maybe have a  list of languages on page 1. This way, we know what language we expect, and they will be forced to read the message about language freedom.

**Comment by leouieda** [comment]
> What is your affiliation?

Done

> What is your level of education? --> Maybe add formal or _academic education? since people can argue education is not only academic.

Changed to "highest level of formal/academic education"

>  suggest bringing this paragraph to the first page of the surve

Done but also left it at the end as a reminder since that's where most written responses are.

> How did you manage to include the list of countries!?

Searched for a list of countries and then copy+paste into the survey fields 😉  Tried doing the same for language but couldn't find a good list that worked with copy+paste. So maybe we leave that for another time.

**Comment by leouieda** [comment]
Survey is live!

* Website banner is up
* LinkedIn 🇬🇧 : https://www.linkedin.com/feed/update/urn:li:activity:6975061082943983616
* LinkedIn 🇧🇷 : https://www.linkedin.com/feed/update/urn:li:activity:6975062354954698753

**Comment by leouieda** [comment]
Good morning @MGomezN @aguspesce @santisoler! Whenever you're ready, please make the social media/github/slack posts outlined above and drop a link here for retweets/reshares.

**Comment by MGomezN** [comment]
Twitter https://twitter.com/fatiandoaterra/status/1569366910118109184 ✅
I just now had the idea that we would have better used something like bitly both to shorten the link and to compare how many opened the link vs how many answered it  :P

**Comment by MGomezN** [comment]
> > What is your affiliation?
> 
> Done
> 
> > What is your level of education? --> Maybe add formal or _academic education? since people can argue education is not only academic.
> 
> Changed to "highest level of formal/academic education"
> 
> > suggest bringing this paragraph to the first page of the surve
> 
> Done but also left it at the end as a reminder since that's where most written responses are.
> 
> > How did you manage to include the list of countries!?
> 
> Searched for a list of countries and then copy+paste into the survey fields wink Tried doing the same for language but couldn't find a good list that worked with copy+paste. So maybe we leave that for another time.

@leouieda Thanks for considering my suggestions. You did an amazing job with the survey :)

**Comment by leouieda** [comment]
> I just now had the idea that we would have better used something like bitly both to shorten the link and to compare how many opened the link vs how many answered it


Yes! We could have used a redirect from our website with plausible enabled. It would achieve the same thing. Taking note of this for the reflection we do afterwards on how to improve for next time.

**Comment by leouieda** [comment]
> You did an amazing job with the survey :)

**We** did 😎
